package com.esprit.entities;
// Generated 27 juin 2018 23:49:29 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Amendmentcs generated by hbm2java
 */
@Entity
@Table(name = "amendmentcs", catalog = "bdnetjee")
public class Amendmentcs implements java.io.Serializable {

	private Integer idAm;

	public Amendmentcs() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "IdAm", unique = true, nullable = false)
	public Integer getIdAm() {
		return this.idAm;
	}

	public void setIdAm(Integer idAm) {
		this.idAm = idAm;
	}

}
