package com.esprit.entities;
// Generated 27 juin 2018 23:49:29 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Classes generated by hbm2java
 */
@Entity
@Table(name = "classes", catalog = "bdnetjee")
public class Classes implements java.io.Serializable {

	private Integer idCla;
	private Classes classes;
	private Users users;
	private int classe;
	private Set<Classes> classeses = new HashSet<Classes>(0);
	private Set<Rcprices> rcpriceses = new HashSet<Rcprices>(0);

	public Classes() {
	}

	public Classes(int classe) {
		this.classe = classe;
	}

	public Classes(Classes classes, Users users, int classe, Set<Classes> classeses, Set<Rcprices> rcpriceses) {
		this.classes = classes;
		this.users = users;
		this.classe = classe;
		this.classeses = classeses;
		this.rcpriceses = rcpriceses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idCla", unique = true, nullable = false)
	public Integer getIdCla() {
		return this.idCla;
	}

	public void setIdCla(Integer idCla) {
		this.idCla = idCla;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Classe_idCla")
	public Classes getClasses() {
		return this.classes;
	}

	public void setClasses(Classes classes) {
		this.classes = classes;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_idUser")
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "classe", nullable = false)
	public int getClasse() {
		return this.classe;
	}

	public void setClasse(int classe) {
		this.classe = classe;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "classes")
	public Set<Classes> getClasseses() {
		return this.classeses;
	}

	public void setClasseses(Set<Classes> classeses) {
		this.classeses = classeses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "classes")
	public Set<Rcprices> getRcpriceses() {
		return this.rcpriceses;
	}

	public void setRcpriceses(Set<Rcprices> rcpriceses) {
		this.rcpriceses = rcpriceses;
	}

}
