package com.esprit.entities;
// Generated 27 juin 2018 23:49:29 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Contracts generated by hbm2java
 */
@Entity
@Table(name = "contracts", catalog = "bdnetjee")
public class Contracts implements java.io.Serializable {

	private Integer idCont;
	private Contracts contracts;
	private Users users;
	private Vehicles vehicles;
	private int codeCont;
	private Date dateCre;
	private Date dateDeb;
	private Date dateFin;
	private double paiement;
	private boolean reconductible;
	private String state;
	private Set<Contracts> contractses = new HashSet<Contracts>(0);
	private Set<Warrantyassignments> warrantyassignmentses = new HashSet<Warrantyassignments>(0);

	public Contracts() {
	}

	public Contracts(int codeCont, Date dateCre, Date dateDeb, Date dateFin, double paiement, boolean reconductible) {
		this.codeCont = codeCont;
		this.dateCre = dateCre;
		this.dateDeb = dateDeb;
		this.dateFin = dateFin;
		this.paiement = paiement;
		this.reconductible = reconductible;
	}

	public Contracts(Contracts contracts, Users users, Vehicles vehicles, int codeCont, Date dateCre, Date dateDeb,
			Date dateFin, double paiement, boolean reconductible, String state, Set<Contracts> contractses,
			Set<Warrantyassignments> warrantyassignmentses) {
		this.contracts = contracts;
		this.users = users;
		this.vehicles = vehicles;
		this.codeCont = codeCont;
		this.dateCre = dateCre;
		this.dateDeb = dateDeb;
		this.dateFin = dateFin;
		this.paiement = paiement;
		this.reconductible = reconductible;
		this.state = state;
		this.contractses = contractses;
		this.warrantyassignmentses = warrantyassignmentses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idCont", unique = true, nullable = false)
	public Integer getIdCont() {
		return this.idCont;
	}

	public void setIdCont(Integer idCont) {
		this.idCont = idCont;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Contract_idCont")
	public Contracts getContracts() {
		return this.contracts;
	}

	public void setContracts(Contracts contracts) {
		this.contracts = contracts;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_idUser")
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "vehicle_IdVehicle")
	public Vehicles getVehicles() {
		return this.vehicles;
	}

	public void setVehicles(Vehicles vehicles) {
		this.vehicles = vehicles;
	}

	@Column(name = "codeCont", nullable = false)
	public int getCodeCont() {
		return this.codeCont;
	}

	public void setCodeCont(int codeCont) {
		this.codeCont = codeCont;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateCre", nullable = false, length = 19)
	public Date getDateCre() {
		return this.dateCre;
	}

	public void setDateCre(Date dateCre) {
		this.dateCre = dateCre;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateDeb", nullable = false, length = 19)
	public Date getDateDeb() {
		return this.dateDeb;
	}

	public void setDateDeb(Date dateDeb) {
		this.dateDeb = dateDeb;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateFin", nullable = false, length = 19)
	public Date getDateFin() {
		return this.dateFin;
	}

	public void setDateFin(Date dateFin) {
		this.dateFin = dateFin;
	}

	@Column(name = "paiement", nullable = false, precision = 22, scale = 0)
	public double getPaiement() {
		return this.paiement;
	}

	public void setPaiement(double paiement) {
		this.paiement = paiement;
	}

	@Column(name = "reconductible", nullable = false)
	public boolean isReconductible() {
		return this.reconductible;
	}

	public void setReconductible(boolean reconductible) {
		this.reconductible = reconductible;
	}

	@Column(name = "state")
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contracts")
	public Set<Contracts> getContractses() {
		return this.contractses;
	}

	public void setContractses(Set<Contracts> contractses) {
		this.contractses = contractses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contracts")
	public Set<Warrantyassignments> getWarrantyassignmentses() {
		return this.warrantyassignmentses;
	}

	public void setWarrantyassignmentses(Set<Warrantyassignments> warrantyassignmentses) {
		this.warrantyassignmentses = warrantyassignmentses;
	}

}
