package com.esprit.entities;
// Generated 27 juin 2018 23:49:29 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Customroles generated by hbm2java
 */
@Entity
@Table(name = "customroles", catalog = "bdnetjee")
public class Customroles implements java.io.Serializable {

	private Integer id;
	private String name;
	private Set<Customuserroles> customuserroleses = new HashSet<Customuserroles>(0);

	public Customroles() {
	}

	public Customroles(String name, Set<Customuserroles> customuserroleses) {
		this.name = name;
		this.customuserroleses = customuserroleses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "Name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customroles")
	public Set<Customuserroles> getCustomuserroleses() {
		return this.customuserroleses;
	}

	public void setCustomuserroleses(Set<Customuserroles> customuserroleses) {
		this.customuserroleses = customuserroleses;
	}

}
