package com.esprit.entities;
// Generated 27 juin 2018 23:49:29 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Folders generated by hbm2java
 */
@Entity
@Table(name = "folders", catalog = "bdnetjee")
public class Folders implements java.io.Serializable {

	private Integer idFolder;
	private Vehicles vehicles;
	private String folderTitle;
	private Date modificationDate;
	private int bonusMalus;
	private boolean renewable;
	private int refundedAmount;
	private String comment;

	public Folders() {
	}

	public Folders(Date modificationDate, int bonusMalus, boolean renewable, int refundedAmount, String comment) {
		this.modificationDate = modificationDate;
		this.bonusMalus = bonusMalus;
		this.renewable = renewable;
		this.refundedAmount = refundedAmount;
		this.comment = comment;
	}

	public Folders(Vehicles vehicles, String folderTitle, Date modificationDate, int bonusMalus, boolean renewable,
			int refundedAmount, String comment) {
		this.vehicles = vehicles;
		this.folderTitle = folderTitle;
		this.modificationDate = modificationDate;
		this.bonusMalus = bonusMalus;
		this.renewable = renewable;
		this.refundedAmount = refundedAmount;
		this.comment = comment;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "IdFolder", unique = true, nullable = false)
	public Integer getIdFolder() {
		return this.idFolder;
	}

	public void setIdFolder(Integer idFolder) {
		this.idFolder = idFolder;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Vehicles_IdVehicle")
	public Vehicles getVehicles() {
		return this.vehicles;
	}

	public void setVehicles(Vehicles vehicles) {
		this.vehicles = vehicles;
	}

	@Column(name = "FolderTitle")
	public String getFolderTitle() {
		return this.folderTitle;
	}

	public void setFolderTitle(String folderTitle) {
		this.folderTitle = folderTitle;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModificationDate", nullable = false, length = 19)
	public Date getModificationDate() {
		return this.modificationDate;
	}

	public void setModificationDate(Date modificationDate) {
		this.modificationDate = modificationDate;
	}

	@Column(name = "BonusMalus", nullable = false)
	public int getBonusMalus() {
		return this.bonusMalus;
	}

	public void setBonusMalus(int bonusMalus) {
		this.bonusMalus = bonusMalus;
	}

	@Column(name = "Renewable", nullable = false)
	public boolean isRenewable() {
		return this.renewable;
	}

	public void setRenewable(boolean renewable) {
		this.renewable = renewable;
	}

	@Column(name = "RefundedAmount", nullable = false)
	public int getRefundedAmount() {
		return this.refundedAmount;
	}

	public void setRefundedAmount(int refundedAmount) {
		this.refundedAmount = refundedAmount;
	}

	@Column(name = "Comment", nullable = false)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

}
