package com.esprit.entities;
// Generated 27 juin 2018 23:49:29 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Garages generated by hbm2java
 */
@Entity
@Table(name = "garages", catalog = "bdnetjee")
public class Garages implements java.io.Serializable {

	private String idGarage;
	private String nameGarage;
	private String placeGarage;
	private String managerGarage;
	private Set<Sinisters> sinisterses = new HashSet<Sinisters>(0);

	public Garages() {
	}

	public Garages(String idGarage) {
		this.idGarage = idGarage;
	}

	public Garages(String idGarage, String nameGarage, String placeGarage, String managerGarage,
			Set<Sinisters> sinisterses) {
		this.idGarage = idGarage;
		this.nameGarage = nameGarage;
		this.placeGarage = placeGarage;
		this.managerGarage = managerGarage;
		this.sinisterses = sinisterses;
	}

	@Id

	@Column(name = "IdGarage", unique = true, nullable = false, length = 128)
	public String getIdGarage() {
		return this.idGarage;
	}

	public void setIdGarage(String idGarage) {
		this.idGarage = idGarage;
	}

	@Column(name = "NameGarage")
	public String getNameGarage() {
		return this.nameGarage;
	}

	public void setNameGarage(String nameGarage) {
		this.nameGarage = nameGarage;
	}

	@Column(name = "PlaceGarage")
	public String getPlaceGarage() {
		return this.placeGarage;
	}

	public void setPlaceGarage(String placeGarage) {
		this.placeGarage = placeGarage;
	}

	@Column(name = "ManagerGarage")
	public String getManagerGarage() {
		return this.managerGarage;
	}

	public void setManagerGarage(String managerGarage) {
		this.managerGarage = managerGarage;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "garages")
	public Set<Sinisters> getSinisterses() {
		return this.sinisterses;
	}

	public void setSinisterses(Set<Sinisters> sinisterses) {
		this.sinisterses = sinisterses;
	}

}
