package com.esprit.entities;
// Generated 27 juin 2018 23:49:29 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Historyrows generated by hbm2java
 */
@Entity
@Table(name = "historyrows", catalog = "bdnetjee")
public class Historyrows implements java.io.Serializable {

	private String migrationId;
	private String contextKey;
	private byte[] model;
	private String productVersion;

	public Historyrows() {
	}

	public Historyrows(String migrationId, String contextKey) {
		this.migrationId = migrationId;
		this.contextKey = contextKey;
	}

	public Historyrows(String migrationId, String contextKey, byte[] model, String productVersion) {
		this.migrationId = migrationId;
		this.contextKey = contextKey;
		this.model = model;
		this.productVersion = productVersion;
	}

	@Id

	@Column(name = "MigrationId", unique = true, nullable = false, length = 100)
	public String getMigrationId() {
		return this.migrationId;
	}

	public void setMigrationId(String migrationId) {
		this.migrationId = migrationId;
	}

	@Column(name = "ContextKey", nullable = false, length = 200)
	public String getContextKey() {
		return this.contextKey;
	}

	public void setContextKey(String contextKey) {
		this.contextKey = contextKey;
	}

	@Column(name = "Model")
	public byte[] getModel() {
		return this.model;
	}

	public void setModel(byte[] model) {
		this.model = model;
	}

	@Column(name = "ProductVersion")
	public String getProductVersion() {
		return this.productVersion;
	}

	public void setProductVersion(String productVersion) {
		this.productVersion = productVersion;
	}

}
