package com.esprit.entities;
// Generated 27 juin 2018 23:49:29 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Sinisters generated by hbm2java
 */
@Entity
@Table(name = "sinisters", catalog = "bdnetjee")
public class Sinisters implements java.io.Serializable {

	private Integer idSinister;
	private Garages garages;
	private Vehicles vehicles;

	public Sinisters() {
	}

	public Sinisters(Garages garages, Vehicles vehicles) {
		this.garages = garages;
		this.vehicles = vehicles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "IdSinister", unique = true, nullable = false)
	public Integer getIdSinister() {
		return this.idSinister;
	}

	public void setIdSinister(Integer idSinister) {
		this.idSinister = idSinister;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Garage_IdGarage")
	public Garages getGarages() {
		return this.garages;
	}

	public void setGarages(Garages garages) {
		this.garages = garages;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Vehicle_IdVehicle")
	public Vehicles getVehicles() {
		return this.vehicles;
	}

	public void setVehicles(Vehicles vehicles) {
		this.vehicles = vehicles;
	}

}
