package com.esprit.entities;
// Generated 27 juin 2018 23:49:29 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Thirds generated by hbm2java
 */
@Entity
@Table(name = "thirds", catalog = "bdnetjee")
public class Thirds implements java.io.Serializable {

	private Integer idThird;

	public Thirds() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "IdThird", unique = true, nullable = false)
	public Integer getIdThird() {
		return this.idThird;
	}

	public void setIdThird(Integer idThird) {
		this.idThird = idThird;
	}

}
