package com.esprit.entities;
// Generated 27 juin 2018 23:49:29 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Vdcfranchiselevels generated by hbm2java
 */
@Entity
@Table(name = "vdcfranchiselevels", catalog = "bdnetjee")
public class Vdcfranchiselevels implements java.io.Serializable {

	private Integer idVdcfl;
	private Vdcfranchiselevels vdcfranchiselevels;
	private int flevel;
	private double bprice;
	private double pprice;
	private Set<Warranties> warrantieses = new HashSet<Warranties>(0);
	private Set<Vdcfranchiselevels> vdcfranchiselevelses = new HashSet<Vdcfranchiselevels>(0);

	public Vdcfranchiselevels() {
	}

	public Vdcfranchiselevels(int flevel, double bprice, double pprice) {
		this.flevel = flevel;
		this.bprice = bprice;
		this.pprice = pprice;
	}

	public Vdcfranchiselevels(Vdcfranchiselevels vdcfranchiselevels, int flevel, double bprice, double pprice,
			Set<Warranties> warrantieses, Set<Vdcfranchiselevels> vdcfranchiselevelses) {
		this.vdcfranchiselevels = vdcfranchiselevels;
		this.flevel = flevel;
		this.bprice = bprice;
		this.pprice = pprice;
		this.warrantieses = warrantieses;
		this.vdcfranchiselevelses = vdcfranchiselevelses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idVDCFL", unique = true, nullable = false)
	public Integer getIdVdcfl() {
		return this.idVdcfl;
	}

	public void setIdVdcfl(Integer idVdcfl) {
		this.idVdcfl = idVdcfl;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VDCFranchiseLevel_idVDCFL")
	public Vdcfranchiselevels getVdcfranchiselevels() {
		return this.vdcfranchiselevels;
	}

	public void setVdcfranchiselevels(Vdcfranchiselevels vdcfranchiselevels) {
		this.vdcfranchiselevels = vdcfranchiselevels;
	}

	@Column(name = "FLevel", nullable = false)
	public int getFlevel() {
		return this.flevel;
	}

	public void setFlevel(int flevel) {
		this.flevel = flevel;
	}

	@Column(name = "BPrice", nullable = false, precision = 22, scale = 0)
	public double getBprice() {
		return this.bprice;
	}

	public void setBprice(double bprice) {
		this.bprice = bprice;
	}

	@Column(name = "PPrice", nullable = false, precision = 22, scale = 0)
	public double getPprice() {
		return this.pprice;
	}

	public void setPprice(double pprice) {
		this.pprice = pprice;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vdcfranchiselevels")
	public Set<Warranties> getWarrantieses() {
		return this.warrantieses;
	}

	public void setWarrantieses(Set<Warranties> warrantieses) {
		this.warrantieses = warrantieses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vdcfranchiselevels")
	public Set<Vdcfranchiselevels> getVdcfranchiselevelses() {
		return this.vdcfranchiselevelses;
	}

	public void setVdcfranchiselevelses(Set<Vdcfranchiselevels> vdcfranchiselevelses) {
		this.vdcfranchiselevelses = vdcfranchiselevelses;
	}

}
