package com.esprit.entities;
// Generated 27 juin 2018 23:49:29 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Warranties generated by hbm2java
 */
@Entity
@Table(name = "warranties", catalog = "bdnetjee")
public class Warranties implements java.io.Serializable {

	private Integer idWrr;
	private Vdcfranchiselevels vdcfranchiselevels;
	private Warranties warranties;
	private String title;
	private double cprice;
	private double pprice;
	private int mandatory;
	private Set<Warranties> warrantieses = new HashSet<Warranties>(0);
	private Set<Warrantyassignments> warrantyassignmentses = new HashSet<Warrantyassignments>(0);

	public Warranties() {
	}

	public Warranties(double cprice, double pprice, int mandatory) {
		this.cprice = cprice;
		this.pprice = pprice;
		this.mandatory = mandatory;
	}

	public Warranties(Vdcfranchiselevels vdcfranchiselevels, Warranties warranties, String title, double cprice,
			double pprice, int mandatory, Set<Warranties> warrantieses,
			Set<Warrantyassignments> warrantyassignmentses) {
		this.vdcfranchiselevels = vdcfranchiselevels;
		this.warranties = warranties;
		this.title = title;
		this.cprice = cprice;
		this.pprice = pprice;
		this.mandatory = mandatory;
		this.warrantieses = warrantieses;
		this.warrantyassignmentses = warrantyassignmentses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idWrr", unique = true, nullable = false)
	public Integer getIdWrr() {
		return this.idWrr;
	}

	public void setIdWrr(Integer idWrr) {
		this.idWrr = idWrr;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VDCFranchiseLevel_idVDCFL")
	public Vdcfranchiselevels getVdcfranchiselevels() {
		return this.vdcfranchiselevels;
	}

	public void setVdcfranchiselevels(Vdcfranchiselevels vdcfranchiselevels) {
		this.vdcfranchiselevels = vdcfranchiselevels;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Warranty_idWrr")
	public Warranties getWarranties() {
		return this.warranties;
	}

	public void setWarranties(Warranties warranties) {
		this.warranties = warranties;
	}

	@Column(name = "title")
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "cPrice", nullable = false, precision = 22, scale = 0)
	public double getCprice() {
		return this.cprice;
	}

	public void setCprice(double cprice) {
		this.cprice = cprice;
	}

	@Column(name = "pPrice", nullable = false, precision = 22, scale = 0)
	public double getPprice() {
		return this.pprice;
	}

	public void setPprice(double pprice) {
		this.pprice = pprice;
	}

	@Column(name = "mandatory", nullable = false)
	public int getMandatory() {
		return this.mandatory;
	}

	public void setMandatory(int mandatory) {
		this.mandatory = mandatory;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "warranties")
	public Set<Warranties> getWarrantieses() {
		return this.warrantieses;
	}

	public void setWarrantieses(Set<Warranties> warrantieses) {
		this.warrantieses = warrantieses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "warranties")
	public Set<Warrantyassignments> getWarrantyassignmentses() {
		return this.warrantyassignmentses;
	}

	public void setWarrantyassignmentses(Set<Warrantyassignments> warrantyassignmentses) {
		this.warrantyassignmentses = warrantyassignmentses;
	}

}
