package com.esprit.entities;
// Generated 27 juin 2018 23:49:29 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Wreckreports generated by hbm2java
 */
@Entity
@Table(name = "wreckreports", catalog = "bdnetjee")
public class Wreckreports implements java.io.Serializable {

	private Integer idWreport;
	private Vehicles vehicles;
	private double wreckValue;
	private double indemnity;

	public Wreckreports() {
	}

	public Wreckreports(double wreckValue, double indemnity) {
		this.wreckValue = wreckValue;
		this.indemnity = indemnity;
	}

	public Wreckreports(Vehicles vehicles, double wreckValue, double indemnity) {
		this.vehicles = vehicles;
		this.wreckValue = wreckValue;
		this.indemnity = indemnity;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "IdWReport", unique = true, nullable = false)
	public Integer getIdWreport() {
		return this.idWreport;
	}

	public void setIdWreport(Integer idWreport) {
		this.idWreport = idWreport;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Vehicle_IdVehicle")
	public Vehicles getVehicles() {
		return this.vehicles;
	}

	public void setVehicles(Vehicles vehicles) {
		this.vehicles = vehicles;
	}

	@Column(name = "WreckValue", nullable = false, precision = 22, scale = 0)
	public double getWreckValue() {
		return this.wreckValue;
	}

	public void setWreckValue(double wreckValue) {
		this.wreckValue = wreckValue;
	}

	@Column(name = "Indemnity", nullable = false, precision = 22, scale = 0)
	public double getIndemnity() {
		return this.indemnity;
	}

	public void setIndemnity(double indemnity) {
		this.indemnity = indemnity;
	}

}
